### ISSUE TITLE
Menu is not vertically scrollable

### ISSUE THREAD

**Issue by vikramkakkar** [CouscousPHP/Couscous#125]
I am (trying out) _couscous_ for some documentation that I need to create. Being from java/android side, I can't tell if the scroll-behavior for *menu* is missing or disabled. I would appreciate if you could shed some light on this.

I am using the default (Template-Light) theme files locally from: [Link](https://github.com/CouscousPHP/Template-Light). Not sure if its important: I have only been using _couscous_ with the `preview` option.

**Comment by mnapoli** [comment]
Hi, this is a design choice of that specific template. Either the menu is scrollable with the page, either it's not and that allows to have the left menu always visible (regardless of your vertical position in the page). The former was chosen (because it's a starter template, so it's not necessarily meant for documentation with loads of pages).

You are of course welcome to create your own template and design it however you like, you can start easily by just copy-pasting the default template :)
