### ISSUE TITLE
Install issues.

### ISSUE THREAD

**Issue by JayHoltslander** [CouscousPHP/Couscous#126]
Running:
``curl -OS http://couscous.couscous.phar``
Results in:
``curl: Remote file name has no length!``

Installing via the global installation of Composer works. But running

``couscous preview``

results in:

``-bash: couscous: command not found``

What am I missing here?

**Comment by mnapoli** [comment]
Hi! I'm curious as to where you found the instructions but the correct URL is:

```
curl -OS http://couscous.io/couscous.phar
```

You can also download it manually: http://couscous.io/couscous.phar

If you install using Composer, you must set up global composer dependencies in your `PATH` variable which is a little more work (instructions: http://akrabat.com/global-installation-of-php-tools-with-composer/).

**Comment by mnapoli** [comment]
I'm closing, please comment if there is another issue.

**Comment by JayHoltslander** [comment]
I apologize. I made a typo.

FYI
``curl -OS http://couscous.io/couscous.phar``
results in 
``curl: (56) Recv failure: Connection reset by peer``

Will download manually and try.

**Comment by JayHoltslander** [comment]
Server running on 127.0.0.1:8000

    Warning: array_map(): An error occurred while invoking the map callback in
    phar:///Users/jay/Desktop/couscous.phar/src/Model/WatchList/WatchList.php on line 39
    
                                              
    [InvalidArgumentException]                  
    "2015-09-14 22:21:19" is not a valid date.  
                                              
    preview [--target TARGET] [--] [<address>] [<source>]

Attempting to open http://localhost:8000/ or 127.0.0.1:8000 results in

    This webpage is not available
    ERR_CONNECTION_REFUSED

Running php 5.4.43 on Mac OSX 10.9

**Comment by mnapoli** [comment]
`curl -OS http://couscous.io/couscous.phar` works fine for me, maybe it's a network issue. Downloading it directly (by clicking on the link) works fine for me too.

For the second issue it's because (I guess) you haven't configured PHP's default timezone. That happens when you install PHP, that setting should be configured manually. This is a know issue with PHP that will be resolved in PHP 7 (not released yet), and I can understand it's not obvious if you don't use PHP everyday (this is generally not a problem for PHP devs who configure that on the first day, so that's why it's not something we think about a lot).

To solve this, you should configure the default timezone setting (e.g. set `UTC` as value) in `php.ini` (usually `/etc/php5/cli/php.ini` on Ubuntu/Debian, see also http://stackoverflow.com/questions/20743060/symfony2-and-date-default-timezone-get-it-is-not-safe-to-rely-on-the-system).

We have an open issue (#119) to add a workaround so that users don't have to do that, but it hasn't been implemented yet.

**Comment by cyberbit** [comment]
@JayHoltslander I had this same problem, the workaround in #119 worked for me.

**Comment by JayHoltslander** [comment]
Thanks guys. I'll try that asap.

**Comment by JayHoltslander** [comment]
@mnapoli FYI: Spoke to our network guy re: My download troubles... This was his response:
<img width="829" alt="screen shot 2015-09-21 at 11 47 19 am" src="https://cloud.githubusercontent.com/assets/2069960/10001517/f85731a4-6056-11e5-9ca0-07b4069b5180.png">

**Comment by mnapoli** [comment]
@JayHoltslander thanks that's interesting. Since http://couscous.io is hosted by GitHub (on GitHub pages), I guess that's a DoS protection from them (nothing much we can do :/).

**Comment by williamgilpin** [comment]
I just wanted to add here that I am also a new user (who does not have PHP experience), and I also ran into both of these issues when trying to follow the "Getting Started" instructions on my OSX Yosemite system. My fixes involved downloading `couscous.phar` through my web browser and adding `date.timezone = "America/Los_Angeles"` in my `php.ini` file, which I found in `/etc/`

Everything works now. Thank you for this wonderful tool.

**Comment by mnapoli** [comment]
@williamgilpin thanks for the feedback. FYI the timezone problem has been fixed by https://github.com/CouscousPHP/Couscous/pull/130/files but this hasn't been released yet.

I've opened #131 to improve the documentation for future new users.

**Comment by mnapoli** [comment]
FYI #130 has been released in [1.3.2](https://github.com/CouscousPHP/Couscous/releases/tag/1.3.2).
