### ISSUE TITLE
Warning when deploying via travis

### ISSUE THREAD

**Issue by nicosomb** [CouscousPHP/Couscous#83]
Hi there, 

Since few days, I've got warnings when deploying via Travis. 

```
PHP Warning:  preg_match() expects parameter 2 to be string, array given in /home/travis/build/wallabag/documentation/vendor/erusev/parsedown-extra/ParsedownExtra.php on line 252
```

Full log here: https://api.travis-ci.org/jobs/48611297/log.txt?deansi=true

Nicolas

**Comment by mnapoli** [comment]
Arf this will be a hard one I'm afraid, the bug seems to be in Parsedown Extra…

Warnings happen in `ParsedownExtra->inlineFootnoteMarker()`, so it may be bugging on a footnote link. Do you have any idea which markdown file it could be?

Can you try to copy-paste the content of your markdown file in the Parsdown demo here: http://parsedown.org/extra/ and see if it works?

Can you also try running `./vendor/bin/couscous generate` on your machine to see if you get the same warnings?

At least those are only warnings and the website is still deployed correctly right?

(sorry again for the delay)

**Comment by nicosomb** [comment]
Parsing into parsedown.org seems to be good, and running `couscous generate` too. I will upgrade my couscous installation and I will see if the problem persists. 

I don't think we have footnote in our documentation, I'll check. 

Oh you're right, website is correctly deployed! I was so tired, I didn't see that. Thank you.

**Comment by mnapoli** [comment]
I'm seeing the same warnings locally when running `couscous preview`. The website still looks fine though…

I can't understand the root of the problem though. I wish we would get rid of Parsedown…

**Comment by mnapoli** [comment]
Ah it was just that we were requiring an old version of Parsedown Extra!

I changed updated `composer.json` and it works for me when using the latest version of Couscous!

**Comment by nicosomb** [comment]
You're right. It works fine https://travis-ci.org/wallabag/documentation/builds/49423715
Thanks for your great work. I love my documentation!
