### ISSUE TITLE
Images in preview mode

### ISSUE THREAD

**Issue by TamasBarta** [CouscousPHP/Couscous#90]
When I run `couscous preview`, the preview server doesn't serve the images I reference in my markdown files. Solution would be to copy the images, or even better, the server could use a router that tries the original folder, if no matching file is found in the generated folder. Which one would you prefer? Tonight I could even take a look, and create a PR for this.

**Comment by mnapoli** [comment]
Hi @TamasBarta,

I don't have this problem as long as images are in the `website/` directory. I can see however how it is a problem if images are elsewhere though…

We need to copy the images, because if preview doesn't work, then the website online will not have the images too.

Here are some ideas:

- we could copy all images we can find (we can [exclude directories](http://couscous.io/docs/configuration.html) anyway if necessary)
- we could have a `couscous.yml` option to say "copy all images found in folders [X, Y, …]"

I'd be more in favor of the first solution, it's simpler.

**Comment by mnapoli** [comment]
Was fixed by #113!
