### ISSUE TITLE
Document command line options

### ISSUE THREAD

**Issue by marienfressinaud** [CouscousPHP/Couscous#95]
I was trying to configure Couscous inside a [Docker image](https://www.docker.com/) but default `couscous preview` serves on 127.0.0.1:8000 and it cannot be changed. This causes a problem with Docker. I would like to be able to run preview on 0.0.0.0:8000 at least.

Thanks!

**Comment by mnapoli** [comment]
You can set the address just like for the `php -S` command ([see here](https://github.com/CouscousPHP/Couscous/blob/master/src/Application/Cli/PreviewCommand.php#L45), for example:

```
$ couscous preview 0.0.0.0:8000
```

I used it a couple of time with Vagrant.

I didn't make it the default because I wasn't sure if people wanted the webserver to be accessible by the whole wide world (or at least their wifi co-users)… That could be up to discussion…

Maybe this needs a bit of documentation though!

**Comment by marienfressinaud** [comment]
Thanks, it works fine!

**Comment by mnapoli** [comment]
Another instance that documenting the CLI options is needed: #94

**Comment by mnapoli** [comment]
Was fixed in #109
