### ISSUE TITLE
How to deploy properly?

### ISSUE THREAD

**Issue by martinlindhe** [CouscousPHP/Couscous#99]
Hello. Trying out this project to put some static pages on my github pages.

I got it running locally and used a custom theme, things look good when i check it out with "couscous preview".

Then i tried a deploy.

This is the result: https://martinlindhe.github.io/

I then did some changes and tried another deploy.
Now i got this error:
```
$ couscous deploy
Generating /Users/ml/dev/martinlindhe.github.io to /Users/ml/dev/martinlindhe.github.io/.couscous/generated
[notice] Fetching template from https://github.com/CouscousPHP/Template-Dark

Deploying the website
Cloning https://github.com/martinlindhe/martinlindhe.github.io in /private/var/folders/f3/4ggz4gls3yv215pb_l5_rn_r0000gn/T/couscous_deploy_6SQMZp
Checking out branch gh-pages
Copying generated website
Committing changes



  [Couscous\CommandRunner\CommandException]
  On branch gh-pages
  Your branch is up-to-date with 'origin/gh-pages'.
  nothing to commit, working directory clean
```
my "git log -p" does indeed show the changes I made. 

After some fiddling, i figured, it must be my master branch being on the github page. So i tried reconfiguring my github page project to set default branch to "gh-pages" (is this what i am supposed to do?)

Then i ran another deploy, and got another error:

```
$ couscous deploy
Generating /Users/ml/dev/martinlindhe.github.io to /Users/ml/dev/martinlindhe.github.io/.couscous/generated
[notice] Fetching template from https://github.com/CouscousPHP/Template-Dark

Deploying the website
Cloning https://github.com/martinlindhe/martinlindhe.github.io in /private/var/folders/f3/4ggz4gls3yv215pb_l5_rn_r0000gn/T/couscous_deploy_SGlNV3
Checking out branch gh-pages



  [RuntimeException]
  Unable to create the branch 'gh-pages'
  fatal: A branch named 'gh-pages' already exists.



deploy [--repository="..."] [--branch="..."] [source]
```

yes, the gh-pages exists locally, and remotely;
```
git branch -r -v
  origin/HEAD     -> origin/master
  origin/gh-pages f1b9f8d Website generation with Couscous
  origin/master   ec68264 update
```

Am i doing something obviously wrong here?

**Comment by mnapoli** [comment]
Hi! I think you have stumbled on a problem specific to the "root" GitHub pages (i.e. deploy to your user page https://martinlindhe.github.io/ instead of a project page for example https://martinlindhe.github.io/you-project)…

As explained [here](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages):

> Content from the `master` branch will be used to build and publish your GitHub Pages site.

This is a problem because Couscous deploys by default on the `gh-pages` branch. However there is an option to specify the branch you wish to deploy to:

```
couscous deploy --branch=master
```

But **beware**: Couscous deletes everything from the branch before committing the website. So before running that command, move the website source (i.e. Markdown) to another branch, like `source` or whatever you like.

Then (once it's committed and all) be on the `source` branch and run deploy on master.

Let us know how it goes :)

**Comment by mnapoli** [comment]
By the way if that works, then we should add documentation for that.

**Comment by bradparks** [comment]
hey! i've got the same problem going on and can't let couscous delete the contents of the master branch as I have a "CNAME" file there that maps it to a custom domain (required by Github pages if mapping your domain). Is there another way to do this? I can publish to the `gh-pages` branch fine.... thanks!

**Comment by bradparks** [comment]
ahhh - i see this may be covered in your docs... my bad! thanks!
